### ISSUE TITLE
Suggestion: change `=` operator to `==` and add `!=` in 0.2

### ISSUE THREAD

**Issue by RReverser** [dtolnay/efg#1]
First of all, I think this crate is a great idea! It always irked me how verbose the syntax for `cfg` was compared to regular Rust.

Suggestion: if we're going for syntax simplification, I'd love to also simplify frequent `not(feature = "somefeature")` not only to `!(feature = "somefeature")` but all the way to `feature != "somefeature"`.

It feels a lot more natural to use `!=` operator, but I suspect it will also require changing `=` to more Rust-like `==`. It would be a breaking change, but perhaps a good thing for consistency with the rest of Rust syntax.

**Comment by dtolnay** [comment]
Both of those are already handled by 0.1.0, but are not required. Do you think that they should be required?

**Comment by RReverser** [comment]
Oh, the README doesn't mention them. Perhaps worth showcasing?

I'm not sure what you mean by "required" in this context tbh.

**Comment by dtolnay** [comment]
Sorry I meant &mdash; do you think that the crate should **delete** support for single `=`, and thereby require that those comparisons be written using `==`?

**Comment by RReverser** [comment]
Ah, I don't have a strong opinion on that one. I didn't know the other two were even supported, I guess consider this a merely documentation issue for README :)

**Comment by msrd0** [comment]
I believe neither `=` nor `==` actually make any sense. If I didn't know Rust and I'd see something like `#[efg(feature = "foo" && feature = "bar")]` I'd expect `feature` to be some kind of string, and this expression to always evaluate to `false`. Maybe the syntax could be changed to `feature("bar")` or `features.contains("bar")`?
