### ISSUE TITLE
specifying ranges

### ISSUE THREAD

**Issue by yoshuawuyts** [dtolnay/efg#3]
https://github.com/rust-lang/rfcs/pull/3036 describes a family of predicates to target minimum versions of platform APIs. For example `min_libc_version` would return the version of libc. It was expected that `max_*` variants would be specified eventually as well [^max], allowing ranges of OS versions to be targeted.

Unfortunately the RFC hasn't seen any updates in a while, but the challenges it attempts to address still exist. I'm wondering whether `efg` could help prototype syntax to specify ranges within attributes. It'd be neat if we could target a specific version range Windows by writing something like this:

```rust
#[cfg(windows && os_version >= "6.0.6000" && os_version < "7.3.5000")]
```

Or possibly taking it further and allowing shorthands such as:

```rust
#[cfg(windows && "6.0.6000" <= os_version < "7.3.5000")]
```

I'm not sure what this feature should look like, but I think having the ability to specify ranges using shorthands would be neat as well. What do you think?

[^max]: Being able to specify the maximum OS version is useful when you're writing polyfills for older versions. This would allow a developers to say something like: "This code runs on windows 10+ only", which can be leveraged to produce more optimized code.

**Comment by dtolnay** [comment]
Thanks for the RFC link! I had not seen this. But I would prefer not to build this into this crate.

**Comment by yoshuawuyts** [comment]
> Thanks for the RFC link! I had not seen this. But I would prefer not to build this into this crate.

Completely understandable! It makes sense to build out the `min`/`max` qualifiers as part of Rust's attribute expressions first, before attempting to add anything of the sort to `efg`.

What I do wonder though is how ranges could be expressed using the current syntax? It's probably not important to answer that straight away. But if `efg` ever graduates to an RFC, we would probably want to cover that, possibly under "Future Possibilities"?

## Prior Art
For future reference, I found out today that [CSS Media Queries level 4](https://drafts.csswg.org/mediaqueries/#mq-range-context) introduces a change very similar to this proposal:

__before__
```css
@media screen and (min-width: 500px) and (max-width: 1200px) {
  .bar {
    display: block;
  }
}
```
__after__
```css
@media screen and (500px <= width <= 1200px) {
  .bar {
    display: block;
  }
}
```
